spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
user:
  address:
    max-count: 20

